name: Deploy Backend (EC2 + systemd)

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch: {}

concurrency:
  group: deploy-backend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive server
        run: |
          cd server
          rm -rf node_modules
          zip -r ../server.zip .

      - name: Copy bundle to EC2 (via SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}         # 可以是 ec2-user 或 deploy（见下方说明）
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server.zip"
          target: "/tmp"                            # 上传到临时目录

      - name: Deploy on EC2 & restart myapp (systemd)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
      
            APP_ROOT=/var/www/myapp
            APP_DIR=$APP_ROOT/current
            ZIP=/tmp/server.zip
      
            # 目录准备
            sudo mkdir -p "$APP_DIR" "$APP_ROOT/shared"
            sudo chown -R deploy:deploy "$APP_ROOT"
      
            # ★ 关键：把 /tmp/server.zip 挪到 APP_DIR 并改属主，这样 deploy 用户能删
            sudo mv "$ZIP" "$APP_DIR"/server.zip
            sudo chown deploy:deploy "$APP_DIR"/server.zip
      
            # 下面都用 deploy 身份执行
            sudo -u deploy bash -lc "
              set -e
              cd '$APP_DIR'
      
              # 如使用 nvm
              if command -v nvm >/dev/null 2>&1; then
                . ~/.nvm/nvm.sh
                nvm install 20 >/dev/null 2>&1 || true
                nvm use 20 || true
              fi
      
              unzip -o server.zip
              rm -f server.zip
      
              npm ci
              npx prisma migrate deploy || true
              [ -f tsconfig.json ] && npm run build
            "
      
            sudo systemctl restart myapp
            sudo systemctl status --no-pager --full myapp || true

